name: bug报告
description: 用于报告bug，反馈问题
title: '【Bug】'
labels: ['bug']
assignees: []
body:
  - type: textarea
    attributes:
      label: 问题描述
      description: 清晰描述bug表现
    validations:
      required: true

  - type: textarea
    attributes:
      label: 复现步骤
      description: 请按顺序列出操作步骤
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: 期望结果
      description: 你原本期望它表现成什么样？
    validations:
      required: true

  - type: textarea
    attributes:
      label: 截图
      description: 如果有界面截图或录屏，可以贴在此处
    validations:
      required: false

  - type: textarea
    attributes:
      label: 日志信息
      description: 如果有报错日志或控制台输出，可以贴在此处
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: 确认不是重复问题
      options:
        - label: 我已搜索过现有 Issue，确认没有重复
          required: true

  - type: checkboxes
    attributes:
      label: 你愿意提交 PR 吗？
      description: 这不是必需的，但我们很乐意在贡献过程中为您提供指导，特别是如果你已经很好地理解了如何实现修复
      options:
        - label: 是的，我愿意提交 PR
